apiVersion: v2
name: cogstack-jupyterhub
description: A Helm chart for CogStack Jupyter Hub using official JupyterHub chart
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: jupyterhub
    version: 4.3.2
    repository: https://hub.jupyter.org/helm-chart/
