apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "medcat-trainer-helm.fullname" . }}
  labels:
    {{- include "medcat-trainer-helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "medcat-trainer-helm.selectorLabels" . | nindent 6 }}
  strategy: {{ toYaml .Values.updateStrategy | nindent 4 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        checksum/medcat-trainer-configmap: {{ include (print $.Template.BasePath "/medcat-trainer-configmap.yaml") . | sha256sum }}
        checksum/medcat-trainer-env-configmap: {{ include (print $.Template.BasePath "/medcat-trainer-env-configmap.yaml") . | sha256sum }}
        checksum/medcat-trainer-secret: {{ include (print $.Template.BasePath "/medcat-trainer-secret.yaml") . | sha256sum }}
        checksum/nginx-configmap: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
      labels:
        {{- include "medcat-trainer-helm.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "medcat-trainer-helm.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: medcat-trainer
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: api
              containerPort: {{ .Values.service.apiPort }}
              protocol: TCP
          args:
            - /usr/bin/supervisord
            - -c
            - /etc/supervisord.conf
          envFrom:
            - configMapRef:
                name: {{ include "medcat-trainer-helm.fullname" . }}-env
            - secretRef:
                name: {{ include "medcat-trainer-helm.fullname" . }}-secret
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /home/configs/base.txt
              name: medcat-trainer-config
              subPath: medcat-base.txt
            - mountPath: /etc/supervisord.conf
              name: medcat-trainer-config
              subPath: supervisord.conf 
            - mountPath: /home/api/media
              name: api-media
            - mountPath: /home/api/static
              name: api-static
            {{- if eq .Values.DB_ENGINE "sqlite3" }}  
            - mountPath: /home/api/db
              name: api-db
            - mountPath: /home/api/db-backup
              name: api-db-backup
            {{- end }}
          {{- with .Values.volumeMounts }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: nginx
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.nginxImage.repository }}:{{ .Values.nginxImage.tag }}"
          imagePullPolicy: {{ .Values.nginxImage.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.nginx.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nginx.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf 
            - name: nginx-config
              mountPath: /etc/nginx/sites-enabled/medcattrainer
              subPath: sitesenabled.medcattrainer 
            - mountPath: /home/api/media
              name: api-media
            - mountPath: /home/api/static
              name: api-static
          {{- with .Values.volumeMounts }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: medcat-trainer-config
          configMap:
            name: {{ include "medcat-trainer-helm.fullname" . }}-config
        - name: api-media
          persistentVolumeClaim:
            claimName: {{ include "medcat-trainer-helm.fullname" . }}-api-media
        - name: api-static
          persistentVolumeClaim:
            claimName:  {{ include "medcat-trainer-helm.fullname" . }}-api-static
        {{- if eq .Values.DB_ENGINE "sqlite3" }}
        - name: api-db
          persistentVolumeClaim:
            claimName:  {{ include "medcat-trainer-helm.fullname" . }}-api-db
        - name: api-db-backup
          persistentVolumeClaim:
            claimName: {{ include "medcat-trainer-helm.fullname" . }}-api-db-backup
        {{- end }}
        - name: nginx-config
          configMap:
            name: {{ include "medcat-trainer-helm.fullname" . }}-nginx-config
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.runtimeClassName }}
      runtimeClassName: {{ .Values.runtimeClassName | quote }}
      {{- end }}
