apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "medcat-trainer-helm.fullname" . }}-medcat-trainer-config
  labels:
    {{- include "medcat-trainer-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: medcat-trainer
data:
  # This is mounted in the path for MEDCAT_CONFIG_FILE in the backend. Default to /home/configs/base.txt
  medcat-base.txt: |
{{ .Values.medcatConfig | indent 4 }}
  supervisord.conf: |
    [supervisord]
    nodaemon=true
    user=root
    logfile=/var/log/supervisord.log
    pidfile=/var/run/supervisord.pid

    [program:medcattrainer]
    command=sh -c "exec /home/scripts/run.sh 2>&1 | sed -u 's/^/[medcattrainer] /'"
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
    autorestart=true

    [program:bg-process]
    command=sh -c "exec /home/scripts/run-bg-process.sh 2>&1 | sed -u 's/^/[bg-process] /'"
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
    autorestart=true

    [program:db-backup]
    command=sh -c "exec cron -f -l 2 2>&1 | sed -u 's/^/[db-backup] /'"
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0
    autorestart=true