apiVersion: v1
kind: Service
metadata:
  name: {{ include "medcat-trainer-helm.fullname" . }}-medcat-trainer
  labels:
    {{- include "medcat-trainer-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: medcat-trainer
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if (and (eq .Values.service.type "NodePort") ( .Values.service.nodePort)) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "medcat-trainer-helm.selectorLabels" . | nindent 4 }}
---
