site_name: Cogstack Documentation
site_url: http://localhost:8080/docs/

theme:
  name: material
  favicon: assets/cogstack-logo.png
  logo: assets/cogstack-logo.png
  icon:
    logo: assets/cogstack-logo.png
  palette:
    primary: white

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.expand
    - navigation.indexes
    - navigation.tracking
    - header.autohide
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

docs_dir: docs

nav:
  - Home:
      - Home: index.md
      - Overview:
          - Introduction: overview/introduction.md
          - Data pipelines: overview/Data pipelines.md
          - Elasticsearch: overview/Elasticsearch.md
          - Natural Language Processing: overview/Natural Language Processing.md
  - MedCAT: https://docs.cogstack.org/projects/nlp
  - MedCAT Trainer: https://docs.cogstack.org/projects/medcat-trainer/
  - NiFi: https://docs.cogstack.org/projects/nifi/
  - Platform:
      - Deployment:
          - Deployment Overview: platform/deployment/_index.md
          - Getting Started:
              - Getting Started: platform/deployment/get-started/_index.md
              - Quickstart: platform/deployment/get-started/quickstart.md
          - Helm:
              - Helm Overview: platform/deployment/helm/_index.md
              - Tutorial: platform/deployment/helm/tutorial.md
              - CogStack Helm Module: platform/deployment/helm/cogstack-helm-module.md
              - Troubleshooting: platform/deployment/helm/troubleshooting.md
              - Charts:
                  - Charts Overview: platform/deployment/helm/charts/_index.md
                  - MedCAT Service Helm: platform/deployment/helm/charts/medcat-service-helm.md
                  - MedCAT Trainer Helm: platform/deployment/helm/charts/medcat-trainer-helm.md
          - Examples:
              - Examples Overview: platform/deployment/examples/_index.md
              - AWS Kubernetes EKS: platform/deployment/examples/aws-kubernetes-eks.md
              - Azure Kubernetes AKS: platform/deployment/examples/azure-kubernetes-aks.md
              - OpenStack Kubernetes K3s: platform/deployment/examples/openstack-kubernetes-k3s.md
              - OpenStack Docker: platform/deployment/examples/openstack-docker.md
          - Docker Compose: platform/deployment/reference/docker-compose/_index.md
      - Observability:
          - Observability Overview: platform/observability/_index.md
          - Getting Started:
              - Quickstart: platform/observability/get-started/quickstart.md
              - User Guide Tutorial: platform/observability/get-started/userguide-tutorial.md
          - Setup:
              - Production Setup: platform/observability/setup/production-setup.md
              - Probing: platform/observability/setup/probing.md
              - Telemetry: platform/observability/setup/telemetry.md
              - Alerting: platform/observability/setup/alerting.md
          - Customization:
              - Customization Overview: platform/observability/customization/_index.md
              - Custom Dashboards: platform/observability/customization/custom-dashboards.md
              - Alerts Customization: platform/observability/customization/alerts-customization.md
              - Custom Prometheus Configs: platform/observability/customization/custom-prometheus-configs.md
              - Blackbox Exporter Config: platform/observability/customization/blackbox-exporter-config.md
          - Reference:
              - Project Details: platform/observability/reference/project-details.md
              - Concept Materials: platform/observability/reference/concept-materials.md
              - Quickstart Manual: platform/observability/reference/quickstart-manual.md
              - Understanding Metrics: platform/observability/reference/understanding-metrics.md

plugins:
  - search
  - termynal

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
